import blog_image from "../assets/ilustrations/blog_image.svg";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import TextComponent from "../elements/text/text";

export const blogSections = [
  {
    className: "blogCard",
    imgClass: "blogImg",
    src: blog_image,
    title: "Creative project management and practices for 2021",
    href: "#",
    linkId: "blogLink",
    linkText: "Read more >>",
  },
  {
    className: "blogCard",
    imgClass: "blogImg",
    src: blog_image,
    title: "Creative project management and practices for 2021",
    href: "#",
    linkId: "blogLink",
    linkText: "Read more >>",
  },
  {
    className: "blogCard",
    imgClass: "blogImg",
    src: blog_image,
    title: "Creative project management and practices for 2021",
    href: "#",
    linkId: "blogLink",
    linkText: "Read more >>",
  },
  {
    className: "blogCard",
    imgClass: "blogImg",
    src: blog_image,
    title: "Creative project management and practices for 2021",
    href: "#",
    linkId: "blogLink",
    linkText: "Read more >>",
  },
];

export const levelCrtificaationA = [
  {
    title: (
      <Row>
        <Col>
          <span>Step 1 </span>
        </Col>
        <Col>
          <TextComponent
            className="title-s"
            text="Application to obtain the certificate"
          />
        </Col>
      </Row>
    ),
    content: "",
  },
];

export const contentA = [
  {
    1: (
      <Row>
        <Col>
          <span>1.1</span>
        </Col>
        <Col>
          <TextComponent
            classname="subtitle"
            text="Express your interest by email or complete the booking form online."
          />
        </Col>
      </Row>
    ),
  },
];

export const TableDatas = [
  {
    id: 1,
    certificate: "IPMA-D-2015-8019",
    surname: "Ristic",
    firstName: "Bojan",
    location: "Serbia",
    salutation: "IPMA-D-2015-9012",
    postcode: "18000",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 2,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 3,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 4,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 5,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 6,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 7,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 8,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 9,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 10,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 11,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 12,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 13,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 14,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 15,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 16,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 17,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 18,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 19,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 20,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 21,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 22,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
  {
    id: 23,
    certificate: "IPMA-D-2015-8019",
    surname: "A.Marca",
    firstName: "Fabian",
    location: "Regensdorf",
    salutation: "IPMA-D-2015-8019",
    postcode: "102262",
    certificationDate: new Date(2015, 9, 3),
    certificationStatus: true,
    detail: "",
  },
];
